services:

  postgres:
    image: postgres:18

    container_name: travelline_postgres

    restart: always

    environment:
      POSTGRES_DB: travelline
      POSTGRES_USER: travelline_user
      POSTGRES_PASSWORD: travelline_pass

    ports:
      - "5435:5432"

    volumes:
      - travelline_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travelline_user -d travelline"]
      interval: 5s
      timeout: 5s
      retries: 10



  migrate:

    build: .

    container_name: travelline_migrate

    depends_on:
      postgres:
        condition: service_healthy

    working_dir: /app
    command: python -m backend.migrate

    environment:
      DATABASE_URL: postgresql://travelline_user:travelline_pass@postgres:5432/travelline



  backend:

    build: .

    container_name: travelline_backend

    depends_on:
      migrate:
        condition: service_completed_successfully

    working_dir: /app
    command: python -m uvicorn backend.app.main:app --host 0.0.0.0 --port 8000

    environment:
      DATABASE_URL: postgresql://travelline_user:travelline_pass@postgres:5432/travelline

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    restart: unless-stopped



volumes:
  travelline_pg_data: